#The sequence of triangle numbers is generated by adding the natural numbers.
#The sequence of triangle numbers is generated by adding the natural numbers.
#So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#Let us list the factors of the first seven triangle numbers:
#1: 1
#3: 1,3
#6: 1,2,3,6
#10: 1,2,5,10
#15: 1,3,5,15
#21: 1,3,7,21
#28: 1,2,4,7,14,28
#We can see that 28 is the first triangle number to have over five divisors.
#What is the value of the first triangle number to have over five hundred divisors?
def factorLen(n):
    factors = [1]
    for divisor in xrange(2, (n/2)+1):
        if n%divisor == 0:
            factors.append(divisor)
    factors.append(n)
    
    return len(factors)

def triNumDivCount(n):
    tri_sum = 0
    for i in xrange(1,99999):
        tri_sum += i
        if factorLen(tri_sum) > n:
            return tri_sum, i


if __name__ == '__main__':
    print(triNumDivCount(5))
